APPLICATION_ENV: "dev"
CORS_ALLOWED_ORIGINS: "http://localhost:8085"
API_SPEC: "http://krea-user-management-api.us-east-1.elasticbeanstalk.com/v3/api-docs"
MYSQL_DB_URL: "krea-user-management.cnsys8oquoqw.us-east-1.rds.amazonaws.com:3306"
MYSQL_DB_USERNAME: "root"
MYSQL_DB_PASSWORD: "<please request if necessary>"
JWT_SECRET: "4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c"
JWT_EXPIRATION_TIME: "86400000"